[package]
license = "MIT"

name="orvpass-cli"
version="2.0.0"
edition="2024"

[[bin]]
name="orvpass"
path="src/main.rs"

[dependencies]
orvpass-core={path="../core"}
clap.workspace=true
anyhow.workspace=true
dialoguer.workspace=true
rpassword.workspace=true
aes-gcm = "0.11.1"
argon2.workspace = true
rand.workspace = true
base64 = "0.23.1"
serde.workspace = true
serde_json.workspace = true
dirs = "6.0.0"
arboard = "3.6.1"
