[package]
name = "orvpass-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
zeroize.workspace = true
thiserror.workspace = true
postcard = { version = "1", features = ["alloc"] }
argon2 = "0.5"
chacha20poly1305 = { version = "0.10", features = ["std"] }
hkdf = "0.12"
sha2 = "0.10"
rand = "0.9"
